/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreadRouteRouteImport } from './routes/thread/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadIndexRouteImport } from './routes/thread/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ThreadIdRouteImport } from './routes/thread/$id'
import { Route as ApiThreadRouteRouteImport } from './routes/api/thread/route'
import { Route as ApiChatRouteRouteImport } from './routes/api/chat/route'
import { Route as SettingsStorageIndexRouteImport } from './routes/settings/storage/index'
import { Route as SettingsProvidersIndexRouteImport } from './routes/settings/providers/index'
import { Route as SettingsPreferencesIndexRouteImport } from './routes/settings/preferences/index'
import { Route as ApiThreadIdRouteImport } from './routes/api/thread/$id'
import { Route as ApiSettingsStorageRouteImport } from './routes/api/settings/storage'
import { Route as ApiKeysIdRouteImport } from './routes/api/keys/$id'
import { Route as ApiDatabaseTestRouteImport } from './routes/api/database/test'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStorageTestRouteRouteImport } from './routes/api/storage/test/route'

const AuthRegisterRouteLazyRouteImport = createFileRoute('/auth/register')()
const AuthLoginRouteLazyRouteImport = createFileRoute('/auth/login')()
const AuthRegisterIndexLazyRouteImport = createFileRoute('/auth/register/')()
const AuthLoginIndexLazyRouteImport = createFileRoute('/auth/login/')()

const ThreadRouteRoute = ThreadRouteRouteImport.update({
  id: '/thread',
  path: '/thread',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIndexRoute = ThreadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThreadRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AuthRegisterRouteLazyRoute = AuthRegisterRouteLazyRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/register/route.lazy').then((d) => d.Route),
)
const AuthLoginRouteLazyRoute = AuthLoginRouteLazyRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/login/route.lazy').then((d) => d.Route),
)
const ThreadIdRoute = ThreadIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ThreadRouteRoute,
} as any)
const ApiThreadRouteRoute = ApiThreadRouteRouteImport.update({
  id: '/api/thread',
  path: '/api/thread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRouteRoute = ApiChatRouteRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexLazyRoute = AuthRegisterIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRegisterRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/register/index.lazy').then((d) => d.Route),
)
const AuthLoginIndexLazyRoute = AuthLoginIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLoginRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/login/index.lazy').then((d) => d.Route),
)
const SettingsStorageIndexRoute = SettingsStorageIndexRouteImport.update({
  id: '/storage/',
  path: '/storage/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProvidersIndexRoute = SettingsProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPreferencesIndexRoute =
  SettingsPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const ApiThreadIdRoute = ApiThreadIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiThreadRouteRoute,
} as any)
const ApiSettingsStorageRoute = ApiSettingsStorageRouteImport.update({
  id: '/api/settings/storage',
  path: '/api/settings/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysIdRoute = ApiKeysIdRouteImport.update({
  id: '/api/keys/$id',
  path: '/api/keys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatabaseTestRoute = ApiDatabaseTestRouteImport.update({
  id: '/api/database/test',
  path: '/api/database/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageTestRouteRoute = ApiStorageTestRouteRouteImport.update({
  id: '/api/storage/test',
  path: '/api/storage/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/thread': typeof ThreadRouteRouteWithChildren
  '/api/chat': typeof ApiChatRouteRoute
  '/api/thread': typeof ApiThreadRouteRouteWithChildren
  '/thread/$id': typeof ThreadIdRoute
  '/auth/login': typeof AuthLoginRouteLazyRouteWithChildren
  '/auth/register': typeof AuthRegisterRouteLazyRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/thread/': typeof ThreadIndexRoute
  '/api/storage/test': typeof ApiStorageTestRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/database/test': typeof ApiDatabaseTestRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/settings/storage': typeof ApiSettingsStorageRoute
  '/api/thread/$id': typeof ApiThreadIdRoute
  '/settings/preferences': typeof SettingsPreferencesIndexRoute
  '/settings/providers': typeof SettingsProvidersIndexRoute
  '/settings/storage': typeof SettingsStorageIndexRoute
  '/auth/login/': typeof AuthLoginIndexLazyRoute
  '/auth/register/': typeof AuthRegisterIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteRoute
  '/api/thread': typeof ApiThreadRouteRouteWithChildren
  '/thread/$id': typeof ThreadIdRoute
  '/settings': typeof SettingsIndexRoute
  '/thread': typeof ThreadIndexRoute
  '/api/storage/test': typeof ApiStorageTestRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/database/test': typeof ApiDatabaseTestRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/settings/storage': typeof ApiSettingsStorageRoute
  '/api/thread/$id': typeof ApiThreadIdRoute
  '/settings/preferences': typeof SettingsPreferencesIndexRoute
  '/settings/providers': typeof SettingsProvidersIndexRoute
  '/settings/storage': typeof SettingsStorageIndexRoute
  '/auth/login': typeof AuthLoginIndexLazyRoute
  '/auth/register': typeof AuthRegisterIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/thread': typeof ThreadRouteRouteWithChildren
  '/api/chat': typeof ApiChatRouteRoute
  '/api/thread': typeof ApiThreadRouteRouteWithChildren
  '/thread/$id': typeof ThreadIdRoute
  '/auth/login': typeof AuthLoginRouteLazyRouteWithChildren
  '/auth/register': typeof AuthRegisterRouteLazyRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/thread/': typeof ThreadIndexRoute
  '/api/storage/test': typeof ApiStorageTestRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/database/test': typeof ApiDatabaseTestRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/settings/storage': typeof ApiSettingsStorageRoute
  '/api/thread/$id': typeof ApiThreadIdRoute
  '/settings/preferences/': typeof SettingsPreferencesIndexRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
  '/settings/storage/': typeof SettingsStorageIndexRoute
  '/auth/login/': typeof AuthLoginIndexLazyRoute
  '/auth/register/': typeof AuthRegisterIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/thread'
    | '/api/chat'
    | '/api/thread'
    | '/thread/$id'
    | '/auth/login'
    | '/auth/register'
    | '/settings/'
    | '/thread/'
    | '/api/storage/test'
    | '/api/auth/$'
    | '/api/database/test'
    | '/api/keys/$id'
    | '/api/settings/storage'
    | '/api/thread/$id'
    | '/settings/preferences'
    | '/settings/providers'
    | '/settings/storage'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/thread'
    | '/thread/$id'
    | '/settings'
    | '/thread'
    | '/api/storage/test'
    | '/api/auth/$'
    | '/api/database/test'
    | '/api/keys/$id'
    | '/api/settings/storage'
    | '/api/thread/$id'
    | '/settings/preferences'
    | '/settings/providers'
    | '/settings/storage'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/thread'
    | '/api/chat'
    | '/api/thread'
    | '/thread/$id'
    | '/auth/login'
    | '/auth/register'
    | '/settings/'
    | '/thread/'
    | '/api/storage/test'
    | '/api/auth/$'
    | '/api/database/test'
    | '/api/keys/$id'
    | '/api/settings/storage'
    | '/api/thread/$id'
    | '/settings/preferences/'
    | '/settings/providers/'
    | '/settings/storage/'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ThreadRouteRoute: typeof ThreadRouteRouteWithChildren
  ApiChatRouteRoute: typeof ApiChatRouteRoute
  ApiThreadRouteRoute: typeof ApiThreadRouteRouteWithChildren
  AuthLoginRouteLazyRoute: typeof AuthLoginRouteLazyRouteWithChildren
  AuthRegisterRouteLazyRoute: typeof AuthRegisterRouteLazyRouteWithChildren
  ApiStorageTestRouteRoute: typeof ApiStorageTestRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDatabaseTestRoute: typeof ApiDatabaseTestRoute
  ApiKeysIdRoute: typeof ApiKeysIdRoute
  ApiSettingsStorageRoute: typeof ApiSettingsStorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thread': {
      id: '/thread'
      path: '/thread'
      fullPath: '/thread'
      preLoaderRoute: typeof ThreadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/': {
      id: '/thread/'
      path: '/'
      fullPath: '/thread/'
      preLoaderRoute: typeof ThreadIndexRouteImport
      parentRoute: typeof ThreadRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$id': {
      id: '/thread/$id'
      path: '/$id'
      fullPath: '/thread/$id'
      preLoaderRoute: typeof ThreadIdRouteImport
      parentRoute: typeof ThreadRouteRoute
    }
    '/api/thread': {
      id: '/api/thread'
      path: '/api/thread'
      fullPath: '/api/thread'
      preLoaderRoute: typeof ApiThreadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexLazyRouteImport
      parentRoute: typeof AuthRegisterRouteLazyRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexLazyRouteImport
      parentRoute: typeof AuthLoginRouteLazyRoute
    }
    '/settings/storage/': {
      id: '/settings/storage/'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/providers/': {
      id: '/settings/providers/'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/preferences/': {
      id: '/settings/preferences/'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/api/thread/$id': {
      id: '/api/thread/$id'
      path: '/$id'
      fullPath: '/api/thread/$id'
      preLoaderRoute: typeof ApiThreadIdRouteImport
      parentRoute: typeof ApiThreadRouteRoute
    }
    '/api/settings/storage': {
      id: '/api/settings/storage'
      path: '/api/settings/storage'
      fullPath: '/api/settings/storage'
      preLoaderRoute: typeof ApiSettingsStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/$id': {
      id: '/api/keys/$id'
      path: '/api/keys/$id'
      fullPath: '/api/keys/$id'
      preLoaderRoute: typeof ApiKeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/database/test': {
      id: '/api/database/test'
      path: '/api/database/test'
      fullPath: '/api/database/test'
      preLoaderRoute: typeof ApiDatabaseTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/test': {
      id: '/api/storage/test'
      path: '/api/storage/test'
      fullPath: '/api/storage/test'
      preLoaderRoute: typeof ApiStorageTestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsPreferencesIndexRoute: typeof SettingsPreferencesIndexRoute
  SettingsProvidersIndexRoute: typeof SettingsProvidersIndexRoute
  SettingsStorageIndexRoute: typeof SettingsStorageIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsPreferencesIndexRoute: SettingsPreferencesIndexRoute,
  SettingsProvidersIndexRoute: SettingsProvidersIndexRoute,
  SettingsStorageIndexRoute: SettingsStorageIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ThreadRouteRouteChildren {
  ThreadIdRoute: typeof ThreadIdRoute
  ThreadIndexRoute: typeof ThreadIndexRoute
}

const ThreadRouteRouteChildren: ThreadRouteRouteChildren = {
  ThreadIdRoute: ThreadIdRoute,
  ThreadIndexRoute: ThreadIndexRoute,
}

const ThreadRouteRouteWithChildren = ThreadRouteRoute._addFileChildren(
  ThreadRouteRouteChildren,
)

interface ApiThreadRouteRouteChildren {
  ApiThreadIdRoute: typeof ApiThreadIdRoute
}

const ApiThreadRouteRouteChildren: ApiThreadRouteRouteChildren = {
  ApiThreadIdRoute: ApiThreadIdRoute,
}

const ApiThreadRouteRouteWithChildren = ApiThreadRouteRoute._addFileChildren(
  ApiThreadRouteRouteChildren,
)

interface AuthLoginRouteLazyRouteChildren {
  AuthLoginIndexLazyRoute: typeof AuthLoginIndexLazyRoute
}

const AuthLoginRouteLazyRouteChildren: AuthLoginRouteLazyRouteChildren = {
  AuthLoginIndexLazyRoute: AuthLoginIndexLazyRoute,
}

const AuthLoginRouteLazyRouteWithChildren =
  AuthLoginRouteLazyRoute._addFileChildren(AuthLoginRouteLazyRouteChildren)

interface AuthRegisterRouteLazyRouteChildren {
  AuthRegisterIndexLazyRoute: typeof AuthRegisterIndexLazyRoute
}

const AuthRegisterRouteLazyRouteChildren: AuthRegisterRouteLazyRouteChildren = {
  AuthRegisterIndexLazyRoute: AuthRegisterIndexLazyRoute,
}

const AuthRegisterRouteLazyRouteWithChildren =
  AuthRegisterRouteLazyRoute._addFileChildren(
    AuthRegisterRouteLazyRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ThreadRouteRoute: ThreadRouteRouteWithChildren,
  ApiChatRouteRoute: ApiChatRouteRoute,
  ApiThreadRouteRoute: ApiThreadRouteRouteWithChildren,
  AuthLoginRouteLazyRoute: AuthLoginRouteLazyRouteWithChildren,
  AuthRegisterRouteLazyRoute: AuthRegisterRouteLazyRouteWithChildren,
  ApiStorageTestRouteRoute: ApiStorageTestRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDatabaseTestRoute: ApiDatabaseTestRoute,
  ApiKeysIdRoute: ApiKeysIdRoute,
  ApiSettingsStorageRoute: ApiSettingsStorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
