/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as PricingRouteRouteImport } from './routes/pricing/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as SettingsPreferencesIndexRouteImport } from './routes/settings/preferences/index'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const AuthRegisterRouteLazyRouteImport = createFileRoute('/auth/register')()
const AuthLoginRouteLazyRouteImport = createFileRoute('/auth/login')()
const AuthRegisterIndexLazyRouteImport = createFileRoute('/auth/register/')()
const AuthLoginIndexLazyRouteImport = createFileRoute('/auth/login/')()
const rootServerRouteImport = createServerRootRoute()

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRouteRoute = PricingRouteRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PricingRouteRoute,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRouteLazyRoute = AuthRegisterRouteLazyRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/register/route.lazy').then((d) => d.Route),
)
const AuthLoginRouteLazyRoute = AuthLoginRouteLazyRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/login/route.lazy').then((d) => d.Route),
)
const AuthRegisterIndexLazyRoute = AuthRegisterIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRegisterRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/register/index.lazy').then((d) => d.Route),
)
const AuthLoginIndexLazyRoute = AuthLoginIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLoginRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/login/index.lazy').then((d) => d.Route),
)
const SettingsPreferencesIndexRoute =
  SettingsPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRouteLazyRouteWithChildren
  '/auth/register': typeof AuthRegisterRouteLazyRouteWithChildren
  '/contact': typeof ContactIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/preferences': typeof SettingsPreferencesIndexRoute
  '/auth/login/': typeof AuthLoginIndexLazyRoute
  '/auth/register/': typeof AuthRegisterIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/preferences': typeof SettingsPreferencesIndexRoute
  '/auth/login': typeof AuthLoginIndexLazyRoute
  '/auth/register': typeof AuthRegisterIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRouteLazyRouteWithChildren
  '/auth/register': typeof AuthRegisterRouteLazyRouteWithChildren
  '/contact/': typeof ContactIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/preferences/': typeof SettingsPreferencesIndexRoute
  '/auth/login/': typeof AuthLoginIndexLazyRoute
  '/auth/register/': typeof AuthRegisterIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/projects'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/contact'
    | '/pricing/'
    | '/projects/'
    | '/settings/'
    | '/settings/preferences'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/pricing'
    | '/projects'
    | '/settings'
    | '/settings/preferences'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/projects'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/contact/'
    | '/pricing/'
    | '/projects/'
    | '/settings/'
    | '/settings/preferences/'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRouteRoute: typeof PricingRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AuthLoginRouteLazyRoute: typeof AuthLoginRouteLazyRouteWithChildren
  AuthRegisterRouteLazyRoute: typeof AuthRegisterRouteLazyRouteWithChildren
  ContactIndexRoute: typeof ContactIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof PricingRouteRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexLazyRouteImport
      parentRoute: typeof AuthRegisterRouteLazyRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexLazyRouteImport
      parentRoute: typeof AuthLoginRouteLazyRoute
    }
    '/settings/preferences/': {
      id: '/settings/preferences/'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface PricingRouteRouteChildren {
  PricingIndexRoute: typeof PricingIndexRoute
}

const PricingRouteRouteChildren: PricingRouteRouteChildren = {
  PricingIndexRoute: PricingIndexRoute,
}

const PricingRouteRouteWithChildren = PricingRouteRoute._addFileChildren(
  PricingRouteRouteChildren,
)

interface ProjectsRouteRouteChildren {
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsPreferencesIndexRoute: typeof SettingsPreferencesIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsPreferencesIndexRoute: SettingsPreferencesIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface AuthLoginRouteLazyRouteChildren {
  AuthLoginIndexLazyRoute: typeof AuthLoginIndexLazyRoute
}

const AuthLoginRouteLazyRouteChildren: AuthLoginRouteLazyRouteChildren = {
  AuthLoginIndexLazyRoute: AuthLoginIndexLazyRoute,
}

const AuthLoginRouteLazyRouteWithChildren =
  AuthLoginRouteLazyRoute._addFileChildren(AuthLoginRouteLazyRouteChildren)

interface AuthRegisterRouteLazyRouteChildren {
  AuthRegisterIndexLazyRoute: typeof AuthRegisterIndexLazyRoute
}

const AuthRegisterRouteLazyRouteChildren: AuthRegisterRouteLazyRouteChildren = {
  AuthRegisterIndexLazyRoute: AuthRegisterIndexLazyRoute,
}

const AuthRegisterRouteLazyRouteWithChildren =
  AuthRegisterRouteLazyRoute._addFileChildren(
    AuthRegisterRouteLazyRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRouteRoute: PricingRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AuthLoginRouteLazyRoute: AuthLoginRouteLazyRouteWithChildren,
  AuthRegisterRouteLazyRoute: AuthRegisterRouteLazyRouteWithChildren,
  ContactIndexRoute: ContactIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
